alias b="bundle"
alias d="docker"
alias dc="docker compose"
alias gl="git log --pretty=format:'%Cred%h%Creset %Cgreen%cs %C(blue)%<(24)%an%Creset %s %C(magenta)%d%Creset' --abbrev-commit"
alias gs="git status"
alias k="kubectl"
# alias m="minikube"
# alias mk="minikube kubectl --"
alias n="node"
alias y="yarn"
